### ISSUE TITLE
activations file format

### ISSUE THREAD

**Issue by navta** [abhinavgupta94/DNN-Activation-Brain#1]
Hi,

I'm trying to use activities or activities.realtime file, copy it as a "activations" file, but it seems the format is not right. The python script tells that the activations file should contain "[" and "]", so I get the following error.

  File "deepbrain.py", line 273, in initgl
    data[i].append(ins)
IndexError: list index out of range

In an attempt to find out the activations file format, I'm trying to add vnnet-forward to the recent kaldi, but get failed when running the program

ERROR (vnnet-forward:vFeedforward():nnet-nnet.cc:520) Assertion failed: propagate_buf_.size() >= 2

So could you tell me the activations file format?

Thank you!

**Comment by backpropper** [comment]
I am sorry for the trouble. Actually, vnnet-forward is another function just like the nnet-forward function but it needs to be added first. "activations" is the output of penultimate layer (or any layer you want) of the network (removing the softmax layer). I will update the repo with the modified kaldi version.
